### ISSUE TITLE
Tietomallin luonti

### ISSUE THREAD

**Issue by banton** [PVARKI-projekti/markdown-pvarki-best_practises#3]
# Mistä on kyse?

Projektin omistajana, haluan että järjestelmästä luodaan skaalautuva ja orgaaninen tietomalli, jonka avulla voidaan rakentaa tietovaranto, ML/AI-käytännöt, API-suunnitelmat ja muut tietoon ja sen rakenteisiin perustuvat toiminnot.

## Taustaa

Normaali postaus koostuu itse lähetetystä tiedosta ja siihen liitetystä metadatasta, tai ulkoisten järjestelmien tuottamasta metadatasta.

## 1. vaihe: Postaus

Ensimmäisessä vaiheessa postaus luodaan mobiiliapplikaation avulla, ja sen ydinelementit ovat:

1. Kuva tai video á la Instagram
2. Määrämuotoinen data / avoin tekstikenttä (jälkimmäistä tulisi välttää kuin ruttoa)
3. Paikkatieto
4. Aikatieto
5. Henkilötieto kirjautumisesta (Suomi.fi hash joka voidaan myöhemmin konvertoida taustalla henkilötunnukseksi?)
6. Sensoridata
7. Loput laitteelta saatavat tiedot (määritettävä)

## 2. vaihe: Prosessointi

Jokaisesta 1. vaiheen elementistä voidaan analysoida dataa ja metadataa, aktiivista ja passiivista – ja näiden yhdistelmiä. Esim. mikäli kuvassa on auto, voidaan siitä päätellä malli, vuosi, sijainti, rekisteröintitiedot, sakkotiedot, omistajatiedot jne.

## 3. vaihe: Kategorisointi

Eri käyttäjäryhmillä on erilaisia tarpeita ja tiedot pitää karsinoida käyttötarpeen ja -ryhmien perusteella

Deliverable: Tietomallikonsepti, UML-dokumentti (Tarpeellista??)

**Comment by rambo** [comment]
This looks like it belongs to some other repo...
